### ISSUE TITLE
configs/modules/pose_bottomup/yolov8_pose.yaml missing

### ISSUE THREAD

**Issue by Tengoles** [TrackingLaboratory/tracklab#4]
Hello! was trying to learn how to use a custom detection module and was having problems with the importing part. Following the tutorial to add yolov8_pose it says there should a config example in `configs/modules/pose_bottomup/yolov8_pose.yaml` but it's not there.

**Comment by victorjoos** [comment]
Hello !

Sorry about that, we moved the configs without changing the docs. The config should be in: tracklab/configs/modules/pose_bottomup/yolov8_pose.yaml. and you can look in the whole tracklab/configs/modules directory for other examples of adding a new module.

Hope this helps,
Victor

**Comment by Tengoles** [comment]
There is no yolov8_pose.yaml on https://github.com/TrackingLaboratory/tracklab/tree/main/tracklab/configs/modules/pose_bottomup only yolov8.yaml and openpifpaf.yaml

**Comment by victorjoos** [comment]
We recently changed a lot of the APIs and removed the modules which didn't adhere to the new API, so that might be why it isn't yet there. To give you an idea on how a module is implemented, you can look at any of the other config files (like yolov8 or openpifpaf), and their corresponding classes (the path is in the _target_ key)

It's on my to-do list to update those old modules, but not very urgently.
